coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: true
codecov:
  max_report_age: off
