linters-settings:
  gocyclo:
    min-complexity: 40
  funlen:
    lines: 60
    statements: 40
  gofmt:
    simplify: true
  misspell:
    locale: US
  revive:
    rules:
      - name: unused-parameter
        disabled: true
      - name: receiver-naming
        disabled: true
      - name: redefines-builtin-id
        disabled: true
      - name: exported
        disabled: true
  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - revive
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
  max-same-issues: 30
  max-issues-per-linter: 30
  fix: true
  exclude-files:
    - ".*_test\\.go$"
    - "vendor/.*"
    - "test/.*"

run:
  timeout: 2m
  go: "1.23"
