version: 2
project_name: go-filesystem
builds:
  - binary: mcp-go-filesystem
    id: mcp-go-filesystem-build
    main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/moguyn/mcp-go-filesystem.Version={{.Version}}
      - -X github.com/moguyn/mcp-go-filesystem.Commit={{.Commit}}
      - -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"

dockers:
  - image_templates:
      - "moguyn/mcp-go-filesystem:{{ .Version }}"
      - "moguyn/mcp-go-filesystem:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
    goos: linux
    goarch: amd64
    ids:
      - mcp-go-filesystem-build
