version: 2
project_name: go-filesystem
builds:
  - binary: mcp-go-filesystem
    id: mcp-go-filesystem-build
    main: ./cmd/server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s
      - -w
      - -X github.com/moguyn/mcp-go-filesystem.Version={{.Version}}
      - -X github.com/moguyn/mcp-go-filesystem.Commit={{.Commit}}
      - -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0

snapshot:
  version_template: "{{ .Version }}-SNAPSHOT-{{ .ShortCommit }}"
