name: Go CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: stable

        - name: Lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v1.64
    
        - name: Test with coverage
          run: |
            go test -race -coverprofile=coverage.txt -covermode=atomic ./...
            go tool cover -func=coverage.txt

        - name: Upload coverage report
          uses: codecov/codecov-action@v5
          with:
            file: ./coverage.txt
            token: ${{ secrets.CODECOV_TOKEN }}
