name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build for all platforms
      run: |
        GOOS=linux GOARCH=amd64 go build -o build/mcp-server-filesystem-linux-amd64 ./cmd/server
        GOOS=darwin GOARCH=amd64 go build -o build/mcp-server-filesystem-darwin-amd64 ./cmd/server
        GOOS=windows GOARCH=amd64 go build -o build/mcp-server-filesystem-windows-amd64.exe ./cmd/server

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/mcp-server-filesystem-linux-amd64
        asset_name: mcp-server-filesystem-linux-amd64
        asset_content_type: application/octet-stream

    - name: Upload macOS Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/mcp-server-filesystem-darwin-amd64
        asset_name: mcp-server-filesystem-darwin-amd64
        asset_content_type: application/octet-stream

    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/mcp-server-filesystem-windows-amd64.exe
        asset_name: mcp-server-filesystem-windows-amd64.exe
        asset_content_type: application/octet-stream 